### ISSUE TITLE
Question cookies

### ISSUE THREAD

**Issue by chassain** [Iketaki/MMM-WebView#1]
Hello,

Thanks for this module. Do you know if it s possible to accept automatically cookies ? i have to accept manually with mouse.
thanks again

**Comment by Iketaki** [comment]
Thank you for your comment.

You may be able to do this by running a little Javascript code after loading the page.

I'm currently thinking of adding a feature to this module that allows you to execute Javascript code after the page loads. Please wait a little while for implementation.

Also, if you don't mind, please let me know the website so that I can provide more detailed support.

**Comment by chassain** [comment]
thanks for the response. It will be great to have this. 
Some informations's channels aren't display with embedyoutube module but it's ok with yours. my differents url are https://www.youtube.com/watch?v=Z-Nwo-ypKtM or https://www.cnews.fr/le-direct   ...i will see for javascript code. Have a good day

**Comment by Iketaki** [comment]
@chassain 
Hi. I implemented a new feature that enables to run any JavaScript code after the page loads.
I think this is useful in specific cases, as you need to write JavaScript code that matches the pages to load.

In the case of CNEWS, you can automatically accept cookies with the following config.
```
config: {
  url: "https://www.cnews.fr/le-direct",
  width: "1920px",
  height: "1080px",
  loadedJS: "function func() {const btn = document.getElementById('didomi-notice-agree-button');if (btn) {btn.click();} else {setTimeout(func, 1000);}}func();",
}
```

Thank you for your request.

**Comment by chassain** [comment]
hello,
cookies are here . I tried to rename "agree" with "accepter" but still here.

**Comment by chassain** [comment]
Hello. I understand the function with didomi but no action with click

**Comment by Iketaki** [comment]
Did you update your module? If not done, try update
https://github.com/Iketaki/MMM-WebView/blob/master/README.md#update

**Comment by chassain** [comment]
yes. but no way with another web (same didomi)

**Comment by chassain** [comment]
https://www.bfmtv.com/var/en-direct/

**Comment by Iketaki** [comment]
Hmm...
In my environment, I have succeeded in automatically accepting cookies with the following config.

```
config: {
  url: "https://www.bfmtv.com/var/en-direct/",
  width: "1920px",
  height: "1080px",
  loadedJS: "function func() {const btn = document.getElementById('didomi-notice-agree-button');if (btn) {btn.click();} else {setTimeout(func, 1000);}}func();",
}
```

If you know the details of the error, I may be able to support you, but it's difficult to support you with the current information.
It may be possible if you have details of current behavior, or if you can get the MagicMirror logs using `pm2 logs`, but I cannot guarantee it. Sorry.

**Comment by chassain** [comment]
It's working but only with this module on magicmirror..I thing i have a module no compatible with...i m going to look for..thanks again

**Comment by chassain** [comment]
OK. i have 30 modules running on magicmirror (with mmm pages). your module is working when i disable MMM-CalendarExt2. If it can help something here. thanks again

**Comment by chassain** [comment]
you can close

**Comment by Iketaki** [comment]
> OK. i have 30 modules running on magicmirror (with mmm pages). your module is working when i disable MMM-CalendarExt2. If it can help something here. thanks again

This is helpful. Thank you for your explanation. I'll try to fix the problem later.
