### ISSUE TITLE
Auto refresh possible

### ISSUE THREAD

**Issue by Jonisos** [Iketaki/MMM-WebView#3]
Hey, 
thanks for the module, it works flawlessly! I am just wondering if there is a way to auto-refresh the website?
In particular I want to display an image from a weather API which only gets refreshed once I call the website again. I could also provide the URL if needed.
In the config you mention the "loadedJS", maybe it can be achieved somehow?

Thanks!

**Comment by Iketaki** [comment]
@Jonisos 
Hi! Sorry for late reply.

I just added the auto-refresh feature!
Please check the readme and try it:)

**Comment by Jonisos** [comment]
Hey,
that's great! I already updated the module and it works nicely! Thanks you for the fast implementation. I think this feature could be highlight in your main module description, as it could be useful for a lot of people.

Maybe you know what is causing this: so in my weather image I can see when it was updated and the time changes every 12h even though it set the refresh time to 16min (since new data should be provided every 15min). Do you know if the image is being cached and therefore not update or what's happening? I could also sent you the URL if you're interested.

Edit: Sorry for closing and reopening. I'm kind of new here.

**Comment by Iketaki** [comment]
@Jonisos 
> that's great! I already updated the module and it works nicely! Thanks you for the fast implementation. I think this feature could be highlight in your main module description, as it could be useful for a lot of people.

Thank you for your advice! I'll append the description on the README.

> Maybe you know what is causing this: so in my weather image I can see when it was updated and the time changes every 12h even though it set the refresh time to 16min (since new data should be provided every 15min). Do you know if the image is being cached and therefore not update or what's happening? I could also sent you the URL if you're interested.

Hmm... I have no idea of such a problem...
Could you send me the URL? I'd like to try to reproduce the issue.

**Comment by Iketaki** [comment]
Probably I guess that that is caused by caching, but I want to understand the problem correctly.

**Comment by Jonisos** [comment]
Below is a link to an example graph. In the top bar you can see a time to the right, this time reflects the refresh time. The hours might be from a different timezone but you should be able to see the minutes changing. For example in a browser window I need to hit refresh to change the time and get a new update. 

https://meteogram.cloud3squared.com/getMeteogramX/N4XyA

**Comment by Iketaki** [comment]
@Jonisos 
Sorry for late reply again.
The cache is now ignored when auto-refreshing.
Please update the module and try it :)

**Comment by Jonisos** [comment]
Perfect! It works as expected. Thank you again, very nice :)
